name: code-format-check
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  actions: write
  checks: write
  contents: write
  deployments: read
  id-token: write
  issues: write
  discussions: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: write
  statuses: write
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1
